[project]
name = "file-upload-service"
version = "1.0.0"
description = "Simple file upload service"
readme = "README.md"
authors = [
    { name = "m-wolfram", email = "maxius.2302@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "apscheduler>=3.11.3",
    "cryptography>=50.0.1",
    "flask>=3.1.3",
    "flask-apscheduler>=1.13.1",
    "flask-login>=0.6.3",
    "flask-paginate>=2024.4.12",
    "python-usernames>=1.1.0",
]
